feat: export `CommonResolutions` constant for helping configure new compositions
editframe/editframe-js pull request #23
Opened 2022-03-08 19:30 UTC by alittlebitweird

i.e.

```
import { Editframe, CommonResolutions } from '@editframe/editframjs'
...
const composition = editframe.videos.new({dimensions: CommonResolutions._1080p})
```

thoughts?

2022-03-08 22:18 UTC, brycedev commented
i need more than a moment to think on this

2022-03-09 18:50 UTC, brycedev requested changes

2022-03-09 18:50 UTC, brycedev commented on src/constant/resolutions/index.ts
> +  _4k: { height: 2160, width: 3840 },
let's get rid of 4k and 8k

2022-03-09 18:50 UTC, brycedev commented on src/constant/resolutions/index.ts
> +  _4k: { height: 2160, width: 3840 },
let's get rid of 4k and 8k

2022-03-09 18:51 UTC, brycedev commented
balking a little at these names, but this is certainly a good step for now 👍

2022-03-11 18:58 UTC, brycedev commented
@alittlebitweird bumping this. are we okay to get this merged in?

2022-03-11 19:03 UTC, alittlebitweird commented
> Reference

Yeah I've also just been thinking of whether there's a nicer way to do this but I think its fine for now

2022-03-11 19:15 UTC, merged